export default function Home() {
  return (
    <div className="flex flex-col items-center justify-center h-screen">
      <h1 className="text-6xl font-bold">Welcome to CoffeeCodes</h1>
      <p className="text-lg mt-4">Generated by coffeecodes-init</p>
    </div>
  );
}
